name: Use Centralized CI/CD

on:
  push:
    branches:
      - '*'

jobs:
  build-and-push:
    uses: staleyj15/docker-ci/.github/workflows/docker-push.yml@main
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ECR_REPOSITORY_URI: ${{ secrets.ECR_REPOSITORY_URI }}
